### PR TITLE
Translate to Chinese

### PR DESCRIPTION
**Pull request by xfl03**

### CODE REVIEW

**Comment by xfl03** [comment]
Ehh... I did not see the translation pulled by another person. As you can see, our translations are not similar.... As the author, choosing the best one is good for every user.

**Comment by xbony2** [comment]
There's a [third translation](https://github.com/MatrexsVigil/harvestcraft/pull/44) >.>

**Comment by 3TUSK** [comment]
@xbony2 which makes me unable to translate [this](http://ftb.gamepedia.com/Module:Navbox/Pam%27s_HarvestCraft), because there is no common-agreed translation

**Comment by xbony2** [comment]
You could probably [tweet](https://twitter.com/matrexsvigil) at Pam, but I don't think she'll add a translation without consensus on which one to add.

**Comment by 3TUSK** [comment]
@xbony2 https://twitter.com/bakaxyf/status/713938065417326596 I hope he can help me

**Pull request closed without merging**
