### PR TITLE
Fix Sesame Seed Ore Dictionary Entry

### LINKED ISSUE #42: Sesame seed plant not dropping when planted in Agricraft crop sticks
So I'm helping test a modpack for Tedyhere (Cthulhu Awakens) and I have a Harvestcraft sesame seed plant set up in some Agricraft cropsticks. When the plant is mature, I right click to harvest the plant, and it goes down to 28% grown and doesn't drop a sesame seed. This is with version 1.7.10La of Harvestcraft and version 1.4.5 of Agricraft. Not sure if this is a Harvestcraft bug or an Agricraft bug, will be reporting to Agricraft's dev as well.

### PR DESCRIPTION
**Pull request by Mochnant**
This PR will fix the persistent issue with sesame seeds (the "fruit" output) crops not being dropped from Agricraft crop sticks.

The cause of this issue is name "cropSesame" vs "seedSesameseed".  It is not related to any bug in Agricraft, nor does Agricraft change anything in Harvestcraft code when it loads.  It cannot be fixed in Agricraft, only in Harvestcraft.

@InfinityRaider said :
```
agricraft looks for crop<Name> and seed<Name> pairs in the oredict
```

Because the pair naming is inconsistent, the "fruit" is not dropped.

This will fix #42 and #62, as well as InfinityRaider/AgriCraft#482, InfinityRaider/AgriCraft#588 and InfinityRaider/AgriCraft#628.

@MatrexsVigil Thank you for considering this issue and accepting this PR for resolution so I can finally make some kimchi.  :smile:

### CODE REVIEW

**Comment by InfinityRaider** [comment]
@MatrexsVigil  Why is this closed without a fix/comment?

**Comment by Mochnant** [comment]
@MatrexsVigil Do you really not understand this is an issue?  What's going on with your reluctance to fix this problem?

**Comment by AeroyrHwrdd** [comment]
@Mochnant @InfinityRaider  Pam is no longer updating anything below 1.9 so we're on our own with scripts and ZZZZZ Config.

**Comment by Mochnant** [comment]
@AeroyrHwrdd Thanks for the followup.  That said, considering how long I've been trying get this fixed (with @InfinityRaider 's help, and this PR is not the first attempt), I think we may have been on our own the whole time.

**Comment by darthvader45** [comment]
@MatrexsVigil Can you at least allow someone to maintain the 1.7.10 build for you, saving you from having to do it yourself?  It would be preferable to not being able to use your mod and Agricraft together when harvesting sesame seed.  A script is only a temporary fix.

**Pull request closed without merging**
