### PR TITLE
Create de_DE.lang

### PR DESCRIPTION
**Pull request by ReneMuetti**
Append German Translation :)

Info:
Line 27, 30, 32 has unknown Items (NEI)

### CODE REVIEW

**Comment by Yulife** [comment]
?? There are still many English words that need to be translated (e.g paperbark) and check for your typos (e.g. Apri**K*ose) as well.

**Comment by ReneMuetti** [comment]
hi
As has probably still an error crept :(
I will of course correct - Thank you

Some things are not translated - I know that. These "things" I do not know and even Google could tell me no "solution" for it. For example, all "* Date *" - objects are fully ungekannt for me. Since I do not want anything (intentionally) interpetieren wrong, I have kept the English originals for the time being.

I will of course continually improve and optimize the translations - and complement everything still "open" systematically. Unfortunately, I have no way to get all declared the country-specific specialties.

**Comment by Yulife** [comment]
Instead of just googling the word, add a word of context it. In PHC dates grow on trees - so they kinda are a fruit. Now, googling "date fruit german" would tell you date means "Dattel". If you cannot figure some words out make a list of them and put them here and I'll help you.

**Comment by ReneMuetti** [comment]
Many thanks for the support.
I have the one with the "date" already found out - sometimes you just "tunnel vision" :)

As far as I can see it, 3 translations are still needed.
"Stock" is loud all information an ingredient for other dishes. Other information or even translations I can not find right.

"Leafy Chicken Sandwich" and "Leafy Fish Sandwich" is probably a Sandwitch with fish and chicken plus Lettuce (salad) ....
But I have so no idea how I could most aptly Translate. Therefore, here the englichen terms are still in there.

Otherwise it should I think now fit so.

Regional specialties (which are usually no specific names are) I have intentionally left so. Baklava for example does not make sense to be translated - at least I think

thanks

**Comment by Yulife** [comment]
Stock is "Brühe". It's an overall term for things like chicken stock (Hühnchenbrühe), beef stock (Rinderbrühe) etc.
Yep, leafy is "laubig". But "laubig" isn't really appetizing so use "...mit Salat" for example.
Yeah, Eigennamen of food shouldn't be translated.
Once you think you are done, update this post and I'll take a final look over it.

**Comment by ReneMuetti** [comment]
Thanks for the help / explanation.
I have updated the file.
I think you can now use so :)

**Comment by Yulife** [comment]
Eh, change these words:
Reuse - Fischfalle
Wasser-Fass - Wasserfass
Kürbis -Garten - Kürbisgarten
Rasengarten - Grasgarten
Grüner Garten - Blattgarten
Gemsegarten - Stengelgarten
Everything with Paperbark - Papierrinde
Everything with Sternenfrucht - Sternfrucht
Everything with Lichtnuss - Kerzennuss
Everything with Beet - Rübe to Rote Beete
Okra can stay Okra
Kokoswürfel - Lamimgtonkuchen
Pawlova -Pavlovakuchen
Remove unneccessary "-"
Hochzeitskuchen - Festlicher Kuchen
Hohnig - Honig
Capitalize Gelee Royalé
Check for correct capitalizations and never use commas
Hasch is drugs, lol. Hash means Bratkartoffeln
Schprudelwasser - Sprudelwasser
There are a lot of N-Endungs typos. For example Vanillen Eis is wrong. Vanilleeis would be correct. Don't use the spacebar so often. I'll check over it for a last time but please check your typos.

**Comment by ReneMuetti** [comment]
hello

Thank you for your active support.
Some is even have noticed me, else I've changed to your information out.
I have the entire translation yet eingie views me and made changes. Also in the game I looked at translations in NEI. I hope that it can now be found Verwenduing.
Some terms have / I was very confused.

**Comment by Yulife** [comment]
You forgot about Okra and you wrote sapling and not setzling :)

**Comment by Yulife** [comment]
Other than, looks pretty good.

**Pull request closed without merging**
